import Head from "next/head";
import styles from "@/styles/Home.module.scss";
import Project from "@/components/Project";
import TypeFont from "@/components/utils/TypeFont";
import ScrollAnimation from "@/components/utils/ScrollAnimation";
import { ProjectData } from "@/data/project.data";
import "keen-slider/keen-slider.min.css";
import TechUse from "@/components/TechUse";
import { motion, useAnimation } from "framer-motion";
import Link from "next/link";
import { useEffect, useState } from "react";
import Nav from "@/components/Nav";
import { Page_Section } from "@/data/type";

export default function Home() {
  const [type_anim_complete, setTypeAnimComplete] = useState(false);

  const sentence = {
    hidden: { opacity: 1 },
    visible: {
      opacity: 1,
      transition: {
        delay: 0.0009,
        staggerChildren: 0.1,
      },
    },
  };

  const scrollToSection = (id: any) => {
    const element = document.getElementById(id);

    if (!Object.values(Page_Section).includes(id) || element == null) {
      window.open(id, "_blank");
      return;
    }
    const topPos = element.getBoundingClientRect().top + window.pageYOffset;
    const finalPos = topPos - 70;

    window.scrollTo({ behavior: "smooth", top: finalPos });
  };

  return (
    <>
      <Head>
        <title>Alvis</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
        <link href="https://fonts.googleapis.com/css2?family=Times+New+Roman&display=swap" rel="stylesheet" />
        <link rel="preconnect" href="https://fonts.gstatic.com" />
        <link href="https://fonts.googleapis.com/css2?family=EB+Garamond&display=swap" rel="stylesheet" />
      </Head>

      <main className={styles.main}>
        <Nav scrollToSection={scrollToSection} />
        <div className={styles.intro} id="top">
          <motion.h2 className={styles.intro_txt} variants={sentence} initial="hidden" animate="visible" onAnimationComplete={() => setTypeAnimComplete(true)}>
            {TypeFont("Hello! My name is")} <br />
            <span className={styles.intro_txt_center}>{TypeFont("Alvis Aung.")}</span> <br />
            {TypeFont("I'm a fullstack software engineer.")}
          </motion.h2>

          <ScrollAnimation trigger={type_anim_complete}>
            <button className="button" onClick={() => scrollToSection(Page_Section.portfolio_sec)}>
              View Portfolio
            </button>
          </ScrollAnimation>
        </div>
        <div className={`${styles.portfolio_sec} section`} id={Page_Section.portfolio_sec}>
          <ScrollAnimation delay_time={0}>
            <h4 className={`center ${styles.portfo_head}`}>Portfolio</h4>
          </ScrollAnimation>

          {ProjectData.map((project, id) => (
            <ScrollAnimation delay_time={0} key={id}>
              <Project title={project.title} desc={project.desc} tech_use={project.tech_use} actions={project.actions} img_gp={project.img_gp} />
            </ScrollAnimation>
          ))}
        </div>
        <div className={`${styles.about_me_sec} section`} id={Page_Section.about_me_sec}>
          <ScrollAnimation>
            <h4 className={`center ${styles.portfo_head}`}>About Me</h4>
            <div className={styles.me_gp}>
              <img src="/img/me.jpg" alt="Alvis" className={styles.my_pic} />
              <div className={styles.my_desc}>
                A passionate and detail-oriented full-stack software engineer with over 2 years of experience developing web applications. My expertise lies in using frameworks like React and PHP to build scalable and robust applications. I have a proven track record of delivering high-quality work on time and collaborating effectively with team members.
                <br />
                In addition to my technical skills, I am a natural leader who takes initiative and works well under pressure. I am also an avid reader and enjoy hitting the gym in my free time to stay fit and focused. I am excited to bring my skills and enthusiasm to a new challenge and am committed to making a meaningful contribution to any team I join.
              </div>
            </div>
          </ScrollAnimation>
          <ScrollAnimation>
            <TechUse />
          </ScrollAnimation>
        </div>
        <div className={`section`} id={Page_Section.resume_sec}>
          <ScrollAnimation>
            <h4 className={`center ${styles.portfo_head}`}>Resume</h4>
            <div className={styles.resume_wrap}>
              <a href="/resume.pdf" target="_blank" className="button project-action-btn">
                View Resume
                <img src="/img/viewfile.png" className="icon" />
              </a>
              <a href="/resume.pdf " download className="button project-action-btn">
                download resume
                <img src="/img/download.png" className="icon" />
              </a>
            </div>
          </ScrollAnimation>
        </div>
        <div className="section" id={Page_Section.contact_sec}>
          <ScrollAnimation>
            <h4 className={`center ${styles.portfo_head}`}>Contact Me</h4>
            <div className={styles.contact_icon_gp}>
              <Link href={`mailto:alvisaung@gmail.com`}>
                <img src="/img/email.png" className={styles.contact_icon} />
              </Link>
              <img src="/img/github.png" className={styles.contact_icon} onClick={() => scrollToSection("https://github.com/alvisaung")} />
              <img src="/img/linkedin.png" className={styles.contact_icon} onClick={() => scrollToSection("https://www.linkedin.com/in/alvis-aung-ab660b225/")} />
            </div>
          </ScrollAnimation>
        </div>
      </main>
    </>
  );
}
