import Head from "next/head";
import styles from "@/styles/Home.module.css";
import Project from "@/components/Project";
import TypeFont from "@/components/utils/TypeFont";
import ScrollAnimation from "@/components/utils/ScrollAnimation";
import { ProjectData } from "@/data/project.data";
import "keen-slider/keen-slider.min.css";
import TechUse from "@/components/TechUse";
import { motion, useAnimation } from "framer-motion";
import Link from "next/link";

enum Page_Section {
  portfolio_sec = "portfolio_sec",
  about_me_sec = "about_me_sec",
  resume_sec = "resume_sec",
  contact_sec = "contact_sec",
}

const nav_menu = [
  { name: "Portfolio", id: Page_Section.portfolio_sec },
  { name: "About", id: Page_Section.about_me_sec },
  { name: "Resume", id: Page_Section.resume_sec },
  { name: "Contact", id: Page_Section.contact_sec },
  { name: "Github", id: "https://github.com/alvisaung" },
  { name: "Linkedin", id: "https://www.linkedin.com/in/alvis-aung-ab660b225/" },
];
export default function Home() {
  const scrollToSection = (id: Page_Section) => {
    if (!Object.values(Page_Section).includes(id)) {
      window.open(id, "_blank");
      return;
    }
    const element = document.getElementById(id);
    const topPos = element.getBoundingClientRect().top + window.pageYOffset;
    const finalPos = topPos - 70;

    window.scrollTo({ behavior: "smooth", top: finalPos });
  };

  const sentence = {
    hidden: { opacity: 1 },
    visible: {
      opacity: 1,
      transition: {
        delay: 0.0009,
        staggerChildren: 0.1,
      },
    },
  };
  // const { ref: portfolio_ref, inView } = useInView({ threshold: 0.05 });
  // const { ref: about_me_ref, inView: about_me_in_view } = useInView({ threshold: 0.05 });

  return (
    <>
      <Head>
        <title>Alvis</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <div className="row nav-gp">
          <div className="logo">Logo</div>
          <nav className="link-gp">
            {nav_menu.map((nav) => (
              <ul key={nav.id} className="nav_menu_item" onClick={() => scrollToSection(nav.id)}>
                {nav.name}
              </ul>
            ))}
          </nav>
        </div>
        <div className={styles.intro} id="top">
          <motion.div className={styles.intro_txt} variants={sentence} initial="hidden" animate="visible">
            {TypeFont("Hello! My name is")} <br />
            <span className={styles.intro_txt_center}>{TypeFont("Alvis Aung.")}</span> <br />
            {TypeFont("I'm a fullstack software engineer.")}
          </motion.div>
          <button className="button" style={{ marginTop: 10, fontSize: 22 }} onClick={() => scrollToSection(Page_Section.portfolio_sec)}>
            View Portfolio
          </button>
        </div>
        <div className={`${styles.portfolio_sec} section`} id={Page_Section.portfolio_sec}>
          <ScrollAnimation delay_time={0}>
            <h4 className={`center ${styles.portfo_head}`}>Portfolio</h4>
          </ScrollAnimation>

          {ProjectData.map((project) => (
            <ScrollAnimation delay_time={0}>
              <Project title={project.title} desc={project.desc} tech_use={project.tech_use} actions={project.actions} img_gp={project.img_gp} />
            </ScrollAnimation>
          ))}
        </div>
        <div className={`${styles.about_me_sec} section`} id={Page_Section.about_me_sec}>
          <ScrollAnimation>
            <h4 className={`center ${styles.portfo_head}`}>About Me </h4>
            <div className={styles.me_gp}>
              <img src="/img/me.jpg" alt="Alvis" className={styles.my_pic} />
              <div className={styles.my_desc}>ndustry. Lorem Ipsum has been the ndustry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only fiveindustry's standard dummy text ever since the 1500s, </div>
            </div>
          </ScrollAnimation>
          <ScrollAnimation>
            <TechUse />
          </ScrollAnimation>
        </div>
        <div className={`section`} id={Page_Section.resume_sec}>
          <ScrollAnimation>
            <h4 className={`center ${styles.portfo_head}`}>Resume</h4>
            <div className={styles.resume_wrap}>
              <a href="/resume.pdf" target="_blank" className="button project-action-btn">
                View Resume
                <img src="/img/viewfile.png" className="icon" />
              </a>
              <a href="/resume.pdf " download className="button project-action-btn">
                download resume
                <img src="/img/download.png" className="icon" />
              </a>
            </div>
          </ScrollAnimation>
        </div>
        <div className="section" id={Page_Section.contact_sec}>
          <ScrollAnimation>
            <h4 className={`center ${styles.portfo_head}`}>Contact</h4>
            <div className={styles.contact_icon_gp}>
              <Link href={`mailto:alvisaung@gmail.com`}>
                <img src="/img/email.png" className={styles.contact_icon} />
              </Link>
              <img src="/img/github.png" className={styles.contact_icon} onClick={() => scrollToSection("https://github.com/alvisaung")} />
              <img src="/img/linkedin.png" className={styles.contact_icon} onClick={() => scrollToSection("https://www.linkedin.com/in/alvis-aung-ab660b225/")} />
            </div>
          </ScrollAnimation>
        </div>
      </main>
    </>
  );
}
